// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueGb2JFG_-TqqtS38SNpsKPaDdhnFCuY',
    appId: '1:594473688320:web:837ee9c2d360c8abaae7e5',
    messagingSenderId: '594473688320',
    projectId: 'gestionstock-3c752',
    authDomain: 'gestionstock-3c752.firebaseapp.com',
    storageBucket: 'gestionstock-3c752.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDEIGz-mYEjzc9yKkM-FOkd_-1wJ7KsRk',
    appId: '1:594473688320:android:ab738c651e70305faae7e5',
    messagingSenderId: '594473688320',
    projectId: 'gestionstock-3c752',
    storageBucket: 'gestionstock-3c752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6ziTKUCbrOW8uOaQ431iP12TT2kXAwI',
    appId: '1:594473688320:ios:c78ceacd0581fcf3aae7e5',
    messagingSenderId: '594473688320',
    projectId: 'gestionstock-3c752',
    storageBucket: 'gestionstock-3c752.firebasestorage.app',
    iosBundleId: 'com.example.gestStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6ziTKUCbrOW8uOaQ431iP12TT2kXAwI',
    appId: '1:594473688320:ios:c78ceacd0581fcf3aae7e5',
    messagingSenderId: '594473688320',
    projectId: 'gestionstock-3c752',
    storageBucket: 'gestionstock-3c752.firebasestorage.app',
    iosBundleId: 'com.example.gestStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBueGb2JFG_-TqqtS38SNpsKPaDdhnFCuY',
    appId: '1:594473688320:web:31612aba4277d992aae7e5',
    messagingSenderId: '594473688320',
    projectId: 'gestionstock-3c752',
    authDomain: 'gestionstock-3c752.firebaseapp.com',
    storageBucket: 'gestionstock-3c752.firebasestorage.app',
  );
}
